spring:
  application:
    name: app-consumer
server:
  port: 8002
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka/,http://localhost:8200/eureka/
    fetch-registry: true
    register-with-eureka: true

